### ISSUE TITLE
Card swipe simulation

### ISSUE THREAD

**Issue by bborncr** [uhppoted/uhppote-simulator#10]
I have the simulator running, it has been invaluable for testing ACLs and integrations.

How do I simulate a card swipe?

**Comment by uhppoted** [comment]
Don't know what I would do without it either :-)...

A `swipe` action is just an HTTP request so you can either use something like _Postman_ or just _curl_, e.g.
```
curl -X POST "http://127.0.0.1:8000/uhppote/simulator/405419896/swipe" -H "accept: application/json" -H "Content-Type: application/json" -d '{"door":1,"card-number":8165535,"direction":1}'
```

There are examples in the Makefile for:
- [swipe](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L108)
- [swipe-in](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L111)
- [swipe-out](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L114)
- [passcode](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L117)
- [open door](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L120)
- [close door](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L124)
- [press button](https://github.com/uhppoted/uhppote-simulator/blob/main/Makefile#L124)

I'll make a note to update the README.

**Comment by bborncr** [comment]
Tested and it works! Thanks!

**Comment by uhppoted** [comment]
oh .. **great** !!
