### ISSUE TITLE
Document the HTTP requests for 'swipe', 'open', etc

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-simulator#11]
Ref. [Card swipe simulation](https://github.com/uhppoted/uhppote-simulator/issues/10)

- [x] curl commands
- [x] Postman scripts
- [x] Update OpenAPI doc
- [x] python script
- [x] Remove `new-device`
- [x] Remove duration from `open`

**Comment by twystd** [comment]
Closing - REST API documented with accompanying Python script and Postman collection+environment
