### ISSUE TITLE
docker::uhppote-simulator with --net=host not replying to commands

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-simulator#2]
With the docker version of `uhppote-simulator`, on Ubuntu 20.10:

> docker run --interactive --net=host --name simulator --rm simulator

>  ./bin/uhppote-cli --debug set-listener 405419896 192.168.1.100:60001
>  ... request
>  ...          00000000  17 90 00 00 78 37 2a 18  c0 a8 01 64 61 ea 00 00  |....x7*....da...|
>  ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
>  ...          
>  ... sent 64 bytes to 155.138.151.255:60000
> 
>    ERROR: read udp 155.138.150.146:35544: i/o timeout

The simulator does not receive the command.

**Comment by twystd** [comment]
### Notes:

1. Running _docker_ with `--net=host` binds the to the localhost.
2. `uhppote-cli` defaults to broadcast using the specific LAN broadcast address (e.g. 155.138.151.255) - it was originally coded for use on laptops with both WiFi and LAN connections and the UHPPOTE controllers were on a wired connection.
3. As per the answer to https://stackoverflow.com/questions/29957143/make-docker-use-ipv4-for-port-binding:

> As @daniel-t points out in the comment: github.com/docker/docker/issues/2174 is about showing binding only to IPv6 in netstat, but that is not an issue. As that github issues states:
> 
> When setting up the proxy, Docker requests the loopback address '127.0.0.1', Linux realises this is an address that exists in IPv6 (as ::0) and opens on both (but it is formally an IPv6 socket). When you run netstat it sees this and tells you it is an IPv6 - but it is still listening on IPv4. If you have played with your settings a little, you may have disabled this trick Linux does - by setting net.ipv6.bindv6only = 1.
> 
> In other words, just because you see it as IPv6 only, it is still able to communicate on IPv4 unless you have IPv6 set to only bind on IPv6 with the net.ipv6.bindv6only setting. To be clear, net.ipv6.bindv6only should be 0 - you can run sysctl net.ipv6.bindv6only to verify.
> 

### Workaround

Specify 0.0.0.0:60000 as the _broadcast_ address for `uhppote-cli`:
```
./bin/uhppote-cli --broadcast 0.0.0.0:60000 --debug set-listener 405419896 155.138.151.255:60001
```

This can be also be set in the `/etc/uhppoted/uhppoted.conf` configuration file:
```
# SYSTEM
bind.address = 155.138.151.255:0
broadcast.address = 0.0.0.0:60000
listen.address = 155.138.151.255:60001
...
```
