### ISSUE TITLE
docker::uhppote-simulator with --net=host not broadcasting events

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-simulator#3]
With the docker version of `uhppote-simulator`, on Ubuntu 20.10:

1. Start the _simulator_ docker container:
> docker run --interactive --net=host --name simulator --rm simulator

2. Set the _simulator_ `listen` address and start the CLI _listener_:
>  ./bin/uhppote-cli --debug --broadcast 0.0.0.0:60000 set-listener 405419896 155.138.151.255:60001
>  ./bin/uhppote-cli --debug listen

3. Simulate a _swipe_:
> ` make swipe`

The simulator broadcasts a _swipe_ event but the CLI does not receive it:

>  ...          
>  ... sent 64 bytes to 155.138.151.255:60001
>  ...          00000000  17 20 00 00 78 37 2a 18  46 00 00 00 01 00 03 01  |. ..x7*.F.......|
>  ...          00000010  02 00 01 00 20 20 12 14  12 02 17 06 00 00 00 00  |....  ..........|
>  ...          00000020  00 00 00 00 00 12 02 17  00 00 00 00 00 00 00 00  |................|
>  ...          00000030  00 00 00 20 12 14 00 00  00 00 00 00 00 00 00 00  |... ............|
>  ...  
> 

> ./bin/uhppote-cli --debug listen
> Listening...
>  ... listening
>

**Comment by twystd** [comment]
### Notes:

1. Running _docker_ with `--net=host` binds the to the localhost.

> netstat -tunlp
> ...
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
> tcp6       0      0 :::22                   :::*                    LISTEN      -                   
> tcp6       0      0 :::8000                 :::*                    LISTEN      -                   
> udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
> udp        0      0 155.138.150.146:68      0.0.0.0:*                           -                   
> udp6       0      0 :::60000                :::*                                -   

2. As per the answer to https://stackoverflow.com/questions/29957143/make-docker-use-ipv4-for-port-binding:

> As @daniel-t points out in the comment: github.com/docker/docker/issues/2174 is about showing binding only to IPv6 in netstat, but that is not an issue. As that github issues states:
> 
> When setting up the proxy, Docker requests the loopback address '127.0.0.1', Linux realises this is an address that exists in IPv6 (as ::0) and opens on both (but it is formally an IPv6 socket). When you run netstat it sees this and tells you it is an IPv6 - but it is still listening on IPv4. If you have played with your settings a little, you may have disabled this trick Linux does - by setting net.ipv6.bindv6only = 1.
> 
> In other words, just because you see it as IPv6 only, it is still able to communicate on IPv4 unless you have IPv6 set to only bind on IPv6 with the net.ipv6.bindv6only setting. To be clear, net.ipv6.bindv6only should be 0 - you can run sysctl net.ipv6.bindv6only to verify.
> 

3. `uhppote-cli` defaults to listening on the specific LAN broadcast address (e.g. 155.138.151.255) because it was originally coded for use on laptops with both WiFi and LAN connections and the UHPPOTE controllers were on a wired connection. It does not receive events sent to the LAN broadcast address (firewall?)

4. Specifying a listen address `0.0.0.0:60001` also does not receive events sent to the LAN broadcast address (firewall?)

### Workaround

1. Set the _simulator_ `listener` address to `0.0.0.0:60001`:
```
./bin/uhppote-cli --broadcast 0.0.0.0:60000 --debug set-listener 405419896 0.0.0.0:60001
```
2. Set the _CLI_ `listen` address to `0.0.0.0:60001`:
```
./bin/uhppote-cli --debug --listen 0.0.0.0:60001 listen
```

This can be also be set in the `/etc/uhppoted/uhppoted.conf` configuration file:
```
# SYSTEM
bind.address = 0.0.0.0.0:0
broadcast.address = 0.0.0.0:60000
listen.address = 0.0.0.0:60001
...
```

> make swipe

> ... sent 64 bytes to 0.0.0.0:60001
>  ...          00000000  17 20 00 00 78 37 2a 18  4c 00 00 00 01 00 03 01  |. ..x7*.L.......|
>  ...          00000010  02 00 01 00 20 20 12 14  12 10 52 06 00 00 00 00  |....  ....R.....|
>  ...          00000020  00 00 00 00 00 12 10 52  00 00 00 00 00 00 00 00  |.......R........|
>  ...          00000030  00 00 00 20 12 14 00 00  00 00 00 00 00 00 00 00  |... ............|
>  ...    

> ./bin/uhppote-cli --debug --listen 0.0.0.0:60001 listen
> Listening...
>  ... listening
>  ... received 64 bytes from [::1]:60000
>  ... response
>  ...          00000000  17 20 00 00 78 37 2a 18  4c 00 00 00 01 00 03 01  |. ..x7*.L.......|
>  ...          00000010  02 00 01 00 20 20 12 14  12 10 52 06 00 00 00 00  |....  ....R.....|
>  ...          00000020  00 00 00 00 00 12 10 52  00 00 00 00 00 00 00 00  |.......R........|
>  ...          00000030  00 00 00 20 12 14 00 00  00 00 00 00 00 00 00 00  |... ............|
>  ...          
>  ... listening
> 405419896  76    1   false 3 1     65538      2020-12-14 12:10:52 6   false false false false false false false false 0    2020-12-14 12:10:52 0          0 00 00
> 
>
