### ISSUE TITLE
the parameter -rest 8000 dosn't work

### ISSUE THREAD

**Issue by kBrausew** [uhppoted/uhppote-simulator#4]
the error message is:
listen tcp: address 8443: missing port in address

if tested with and without started UHPPOTED-REST & port 8000 and 8443, message is the always same

**Comment by kBrausew** [comment]
plz closed the ticket...  me bad -> RTFM

with "-rest 0.0.0.0:8000" all OK


BTW: ioBroker is in process, but take longer as planed

**Comment by uhppoted** [comment]
<smile> self closing tickets are the best kind!

re. ioBroker. Oh good - I was wondering how it was going (Ha! Just found your project - I'll add it to my 'watching' list)
